import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

// Translation dictionary with complete translations
const translations: Record<string, Record<string, string>> = {
  en: {
    // Navigation
    'Dashboard': 'Dashboard',
    'Marketplace': 'Marketplace',
    'Verification': 'Verification',
    'Learning': 'Learning',
    'Login': 'Login',
    'Logout': 'Logout',
    
    // Homepage
    'Empowering Farmers': 'Empowering Farmers',
    'Protecting Planet': 'Protecting Planet',
    'Join thousands of farmers earning income from environmental conservation through AI-powered carbon credit verification and blockchain technology.': 'Join thousands of farmers earning income from environmental conservation through AI-powered carbon credit verification and blockchain technology.',
    'Start Earning Today': 'Start Earning Today',
    'Learn More': 'Learn More',
    'Revolutionary Features': 'Revolutionary Features',
    'Advanced technology made simple for farmers to participate in the global carbon economy': 'Advanced technology made simple for farmers to participate in the global carbon economy',
    'How It Works': 'How It Works',
    'Simple steps to start earning from your environmental efforts': 'Simple steps to start earning from your environmental efforts',
    'Ready to Start Earning?': 'Ready to Start Earning?',
    'Join thousands of farmers making a difference and earning income': 'Join thousands of farmers making a difference and earning income',
    'Get Started Now': 'Get Started Now',
    
    // Stats
    'Farmers Connected': 'Farmers Connected',
    'Carbon Credits Generated': 'Carbon Credits Generated',
    'Farmer Earnings': 'Farmer Earnings',
    'Verification Accuracy': 'Verification Accuracy',
    
    // Features
    'AI-Powered Verification': 'AI-Powered Verification',
    'Satellite and AI technology verify your environmental impact automatically': 'Satellite and AI technology verify your environmental impact automatically',
    'Blockchain Security': 'Blockchain Security',
    'Transparent, tamper-proof carbon credit tracking on blockchain': 'Transparent, tamper-proof carbon credit tracking on blockchain',
    'Global Marketplace': 'Global Marketplace',
    'Connect with global buyers and trade carbon credits seamlessly': 'Connect with global buyers and trade carbon credits seamlessly',
    'Local Language Support': 'Local Language Support',
    'WhatsApp, IVR, and mobile app access in your local language': 'WhatsApp, IVR, and mobile app access in your local language',
    'Earn While You Save': 'Earn While You Save',
    'Generate income from your environmental conservation efforts': 'Generate income from your environmental conservation efforts',
    'BECKN Integration': 'BECKN Integration',
    'Interoperable ecosystem connecting all stakeholders': 'Interoperable ecosystem connecting all stakeholders',
    
    // Dashboard
    'Welcome back': 'Welcome back',
    'Track your environmental impact and earnings': 'Track your environmental impact and earnings',
    'Submit New Project': 'Submit New Project',
    'Record environmental actions': 'Record environmental actions',
    'List Credits for Sale': 'List Credits for Sale',
    'Sell in marketplace': 'Sell in marketplace',
    'Learn & Earn': 'Learn & Earn',
    'Complete training modules': 'Complete training modules',
    'Total Credits Earned': 'Total Credits Earned',
    'Total Earnings': 'Total Earnings',
    'Carbon Impact': 'Carbon Impact',
    'Verification Score': 'Verification Score',
    'Recent Projects': 'Recent Projects',
    'Recent Transactions': 'Recent Transactions',
    'Environmental Impact': 'Environmental Impact',
    'Trees Equivalent': 'Trees Equivalent',
    'Clean Energy': 'Clean Energy',
    'People Inspired': 'People Inspired',
    
    // Common
    'credits': 'credits',
    'GramCredits': 'GramCredits',
    'INR': 'INR',
    'CO2 Tons Saved': 'CO2 Tons Saved',
    'Accuracy': 'Accuracy',
    'verified': 'verified',
    'pending': 'pending',
    'rejected': 'rejected',
    'Verified': 'Verified',
    'Beginner': 'Beginner',
    'Intermediate': 'Intermediate',
    'Advanced': 'Advanced',
    'All Categories': 'All Categories',
    'Renewable Energy': 'Renewable Energy',
    'Forestry': 'Forestry',
    'Agriculture': 'Agriculture',
    'Conservation': 'Conservation',
    'All Prices': 'All Prices',
    'Filter': 'Filter',
    'Save': 'Save',
    'Edit': 'Edit',
    'Full Name': 'Full Name',
    'Email': 'Email',
    'Phone Number': 'Phone Number',
    'Location': 'Location',
    'Farm Size': 'Farm Size',
    'Preferred Language': 'Preferred Language',
    'Bio': 'Bio',
    'Profile Information': 'Profile Information',
    'Achievements': 'Achievements',
    'Performance Stats': 'Performance Stats',
    'Quick Actions': 'Quick Actions',
    'View Analytics': 'View Analytics',
    'Share Profile': 'Share Profile',
    'View Certificates': 'View Certificates',
    'WhatsApp Integration': 'WhatsApp Integration',
    'Get updates and notifications directly on WhatsApp': 'Get updates and notifications directly on WhatsApp',
    'Connected': 'Connected',
    'Number': 'Number',
    'Learning Hub': 'Learning Hub',
    'Learn, earn, and grow with our gamified green literacy platform': 'Learn, earn, and grow with our gamified green literacy platform',
    'Lessons Completed': 'Lessons Completed',
    'Points Earned': 'Points Earned',
    'Badges Earned': 'Badges Earned',
    'Courses Completed': 'Courses Completed',
    'Courses': 'Courses',
    'Achievements': 'Achievements',
    'Leaderboard': 'Leaderboard',
    'points': 'points',
    'Start Course': 'Start Course',
    'Continue': 'Continue',
    'Download Certificate': 'Download Certificate',
    'Complete Next Lesson': 'Complete Next Lesson',
    'Complete Course': 'Complete Course',
    'Community Challenges': 'Community Challenges',
    'Recent Activity': 'Recent Activity',
    'Project Verification': 'Project Verification',
    'Submit your environmental projects for AI-powered verification': 'Submit your environmental projects for AI-powered verification',
    'Submit Project': 'Submit Project',
    'Verification History': 'Verification History',
    'Real-time Monitoring': 'Real-time Monitoring',
    'Project Title': 'Project Title',
    'Project Type': 'Project Type',
    'Select Project Type': 'Select Project Type',
    'Project Location': 'Project Location',
    'Project Description': 'Project Description',
    'Upload Evidence': 'Upload Evidence',
    'Submit for Verification': 'Submit for Verification',
    'Carbon Credits Marketplace': 'Carbon Credits Marketplace',
    'Connect with global buyers and sellers in the carbon credit ecosystem': 'Connect with global buyers and sellers in the carbon credit ecosystem',
    'Avg. Price/Credit': 'Avg. Price/Credit',
    'Credits Available': 'Credits Available',
    'Active Sellers': 'Active Sellers',
    'Active Buyers': 'Active Buyers',
    'Available Credits': 'Available Credits',
    'Buy Credits': 'Buy Credits',
    'View Details': 'View Details',
    'List Your Credits': 'List Your Credits',
    'Start selling today': 'Start selling today',
    'Price Alerts': 'Price Alerts',
    'Get notified of price changes': 'Get notified of price changes',
    'Market Trends': 'Market Trends',
    'Enter address or coordinates': 'Enter address or coordinates',
    'Describe your environmental project in detail...': 'Describe your environmental project in detail...',
    'Drop files here or click to browse': 'Drop files here or click to browse',
    'Support: JPG, PNG, PDF, MP4 (max 10MB)': 'Support: JPG, PNG, PDF, MP4 (max 10MB)',
    'AI Verification Process': 'AI Verification Process',
    'Data Collection': 'Data Collection',
    'Satellite imagery and project data analysis': 'Satellite imagery and project data analysis',
    'AI Analysis': 'AI Analysis',
    'Machine learning algorithms verify impact': 'Machine learning algorithms verify impact',
    'Blockchain Recording': 'Blockchain Recording',
    'Results stored on immutable ledger': 'Results stored on immutable ledger',
    'Credit Generation': 'Credit Generation',
    'GramCredits issued based on verified impact': 'GramCredits issued based on verified impact',
    'Verification Benefits': 'Verification Benefits',
    '95%+ accuracy with AI verification': '95%+ accuracy with AI verification',
    '24-48 hour verification time': '24-48 hour verification time',
    'Transparent blockchain recording': 'Transparent blockchain recording',
    'Instant credit generation': 'Instant credit generation',
    'Global marketplace access': 'Global marketplace access',
    'Real-time impact tracking': 'Real-time impact tracking',
    'Live Satellite Feed': 'Live Satellite Feed',
    'Real-time satellite imagery of your project locations': 'Real-time satellite imagery of your project locations',
    'Environmental Metrics': 'Environmental Metrics',
    'Carbon Sequestration': 'Carbon Sequestration',
    'Energy Generation': 'Energy Generation',
    'Water Saved': 'Water Saved',
    'Soil Health': 'Soil Health',
    'Project Status': 'Project Status',
    'AI Insights': 'AI Insights',
    'Recommendation': 'Recommendation',
    'Achievement': 'Achievement',
    'lessons completed': 'lessons completed',
    'credits available': 'credits available',
    'per credit': 'per credit',
    'Search sellers, projects, or locations...': 'Search sellers, projects, or locations...',
    'Credits Earned': 'Credits Earned',
    'Type': 'Type',
    'Confidence': 'Confidence',
    'Register & Verify': 'Register & Verify',
    'Sign up and verify your farming activities through our AI system': 'Sign up and verify your farming activities through our AI system',
    'Take Climate Action': 'Take Climate Action',
    'Plant trees, adopt solar energy, or restore ecosystems': 'Plant trees, adopt solar energy, or restore ecosystems',
    'Get Verified': 'Get Verified',
    'AI and satellite technology verify your environmental impact': 'AI and satellite technology verify your environmental impact',
    'Earn Credits': 'Earn Credits',
    'Receive GramCredits and trade them in the global marketplace': 'Receive GramCredits and trade them in the global marketplace',
    'Water Conservation': 'Water Conservation',
    'Soil Conservation': 'Soil Conservation',
    'Waste Management': 'Waste Management',
    'Energy Efficiency': 'Energy Efficiency',
    'Introduction to Carbon Credits': 'Introduction to Carbon Credits',
    'Learn the basics of carbon markets and how they work': 'Learn the basics of carbon markets and how they work',
    'Sustainable Farming Practices': 'Sustainable Farming Practices',
    'Modern techniques for eco-friendly agriculture': 'Modern techniques for eco-friendly agriculture',
    'Renewable Energy Systems': 'Renewable Energy Systems',
    'Solar, wind, and biogas solutions for farmers': 'Solar, wind, and biogas solutions for farmers',
    'Water Conservation Techniques': 'Water Conservation Techniques',
    'Efficient irrigation and rainwater harvesting': 'Efficient irrigation and rainwater harvesting',
    'Blockchain Fundamentals': 'Blockchain Fundamentals',
    'Understanding blockchain technology for carbon credits': 'Understanding blockchain technology for carbon credits',
    'Climate Change Adaptation': 'Climate Change Adaptation',
    'Preparing your farm for climate resilience': 'Preparing your farm for climate resilience',
    'First Steps': 'First Steps',
    'Complete your first lesson': 'Complete your first lesson',
    'Knowledge Seeker': 'Knowledge Seeker',
    'Complete 5 lessons': 'Complete 5 lessons',
    'Carbon Expert': 'Carbon Expert',
    'Master carbon credit fundamentals': 'Master carbon credit fundamentals',
    'Sustainable Farmer': 'Sustainable Farmer',
    'Complete all farming courses': 'Complete all farming courses',
    'Community Leader': 'Community Leader',
    'Help 10 other farmers': 'Help 10 other farmers',
    'Green Pioneer': 'Green Pioneer',
    'Complete all courses': 'Complete all courses',
    'Total Labels': 'Total Labels',
    'Projects Completed': 'Projects Completed',
    'Income Generated': 'Income Generated',
    'completed': 'completed',
    'Monthly Tree Planting': 'Monthly Tree Planting',
    'Plant 1000 trees as a community': 'Plant 1000 trees as a community',
    'Solar Energy Drive': 'Solar Energy Drive',
    'Install solar panels in 50 farms': 'Install solar panels in 50 farms',
    'Join Challenge': 'Join Challenge',
    'Voice Interface': 'Voice Interface',
    'Press and hold to speak': 'Press and hold to speak',
    'Listening...': 'Listening...',
    'Processing...': 'Processing...',
    'Speak now': 'Speak now',
    'Voice command recognized': 'Voice command recognized',
    'Language changed to': 'Language changed to',
    'English': 'English',
    'Hindi': 'हिंदी',
    'Telugu': 'తెలుగు',
    'Tamil': 'தமிழ்',
    'Bengali': 'বাংলা',
    'Gujarati': 'ગુજરાતી',
    'Marathi': 'मराठी',
    'Punjabi': 'ਪੰਜਾਬੀ',
    'Kannada': 'ಕನ್ನಡ',
    'Malayalam': 'മലയാളം'
  },
  hi: {
    // Navigation
    'Dashboard': 'डैशबोर्ड',
    'Marketplace': 'बाज़ार',
    'Verification': 'सत्यापन',
    'Learning': 'सीखना',
    'Login': 'लॉगिन',
    'Logout': 'लॉगआउट',
    
    // Homepage
    'Empowering Farmers': 'किसानों को सशक्त बनाना',
    'Protecting Planet': 'पृथ्वी की रक्षा',
    'Join thousands of farmers earning income from environmental conservation through AI-powered carbon credit verification and blockchain technology.': 'AI-संचालित कार्बन क्रेडिट सत्यापन और ब्लॉकचेन तकनीक के माध्यम से पर्यावरण संरक्षण से आय अर्जित करने वाले हजारों किसानों से जुड़ें।',
    'Start Earning Today': 'आज ही कमाना शुरू करें',
    'Learn More': 'और जानें',
    'Revolutionary Features': 'क्रांतिकारी सुविधाएं',
    'Advanced technology made simple for farmers to participate in the global carbon economy': 'किसानों के लिए वैश्विक कार्बन अर्थव्यवस्था में भाग लेने के लिए उन्नत तकनीक को सरल बनाया गया',
    'How It Works': 'यह कैसे काम करता है',
    'Simple steps to start earning from your environmental efforts': 'अपने पर्यावरणीय प्रयासों से कमाई शुरू करने के लिए सरल कदम',
    'Ready to Start Earning?': 'कमाना शुरू करने के लिए तैयार हैं?',
    'Join thousands of farmers making a difference and earning income': 'बदलाव लाने और आय अर्जित करने वाले हजारों किसानों से जुड़ें',
    'Get Started Now': 'अभी शुरू करें',
    
    // Dashboard
    'Welcome back': 'वापस स्वागत है',
    'Track your environmental impact and earnings': 'अपने पर्यावरणीय प्रभाव और आय को ट्रैक करें',
    'Submit New Project': 'नई परियोजना जमा करें',
    'Record environmental actions': 'पर्यावरणीय कार्यों को रिकॉर्ड करें',
    'List Credits for Sale': 'बिक्री के लिए क्रेडिट सूचीबद्ध करें',
    'Sell in marketplace': 'बाज़ार में बेचें',
    'Learn & Earn': 'सीखें और कमाएं',
    'Complete training modules': 'प्रशिक्षण मॉड्यूल पूरे करें',
    'Total Credits Earned': 'कुल अर्जित क्रेडिट',
    'Total Earnings': 'कुल आय',
    'Carbon Impact': 'कार्बन प्रभाव',
    'Verification Score': 'सत्यापन स्कोर',
    'Recent Projects': 'हाल की परियोजनाएं',
    'Recent Transactions': 'हाल के लेनदेन',
    'Environmental Impact': 'पर्यावरणीय प्रभाव',
    'Trees Equivalent': 'पेड़ों के बराबर',
    'Clean Energy': 'स्वच्छ ऊर्जा',
    'People Inspired': 'प्रेरित लोग',
    
    // Common
    'credits': 'क्रेडिट',
    'GramCredits': 'ग्रामक्रेडिट',
    'INR': 'रुपये',
    'CO2 Tons Saved': 'CO2 टन बचाया गया',
    'Accuracy': 'सटीकता',
    'verified': 'सत्यापित',
    'pending': 'लंबित',
    'rejected': 'अस्वीकृत',
    'Verified': 'सत्यापित',
    'Beginner': 'शुरुआती',
    'Intermediate': 'मध्यम',
    'Advanced': 'उन्नत',
    'All Categories': 'सभी श्रेणियां',
    'Renewable Energy': 'नवीकरणीय ऊर्जा',
    'Forestry': 'वानिकी',
    'Agriculture': 'कृषि',
    'Conservation': 'संरक्षण',
    'All Prices': 'सभी मूल्य',
    'Filter': 'फ़िल्टर',
    'Save': 'सहेजें',
    'Edit': 'संपादित करें',
    'Full Name': 'पूरा नाम',
    'Email': 'ईमेल',
    'Phone Number': 'फ़ोन नंबर',
    'Location': 'स्थान',
    'Farm Size': 'खेत का आकार',
    'Preferred Language': 'पसंदीदा भाषा',
    'Bio': 'जीवनी',
    'Profile Information': 'प्रोफ़ाइल जानकारी',
    'Achievements': 'उपलब्धियां',
    'Performance Stats': 'प्रदर्शन आंकड़े',
    'Quick Actions': 'त्वरित कार्य',
    'View Analytics': 'विश्लेषण देखें',
    'Share Profile': 'प्रोफ़ाइल साझा करें',
    'View Certificates': 'प्रमाणपत्र देखें',
    'WhatsApp Integration': 'WhatsApp एकीकरण',
    'Get updates and notifications directly on WhatsApp': 'WhatsApp पर सीधे अपडेट और सूचनाएं प्राप्त करें',
    'Connected': 'जुड़ा हुआ',
    'Number': 'नंबर',
    'Learning Hub': 'शिक्षा केंद्र',
    'Learn, earn, and grow with our gamified green literacy platform': 'हमारे गेमिफाइड हरित साक्षरता मंच के साथ सीखें, कमाएं और बढ़ें',
    'Lessons Completed': 'पूरे किए गए पाठ',
    'Points Earned': 'अर्जित अंक',
    'Badges Earned': 'अर्जित बैज',
    'Courses Completed': 'पूरे किए गए कोर्स',
    'Courses': 'कोर्स',
    'Achievements': 'उपलब्धियां',
    'Leaderboard': 'लीडरबोर्ड',
    'points': 'अंक',
    'Start Course': 'कोर्स शुरू करें',
    'Continue': 'जारी रखें',
    'Download Certificate': 'प्रमाणपत्र डाउनलोड करें',
    'Complete Next Lesson': 'अगला पाठ पूरा करें',
    'Complete Course': 'कोर्स पूरा करें',
    'Community Challenges': 'सामुदायिक चुनौतियां',
    'Recent Activity': 'हाल की गतिविधि',
    'Project Verification': 'परियोजना सत्यापन',
    'Submit your environmental projects for AI-powered verification': 'AI-संचालित सत्यापन के लिए अपनी पर्यावरणीय परियोजनाएं जमा करें',
    'Submit Project': 'परियोजना जमा करें',
    'Verification History': 'सत्यापन इतिहास',
    'Real-time Monitoring': 'वास्तविक समय निगरानी',
    'Project Title': 'परियोजना शीर्षक',
    'Project Type': 'परियोजना प्रकार',
    'Select Project Type': 'परियोजना प्रकार चुनें',
    'Project Location': 'परियोजना स्थान',
    'Project Description': 'परियोजना विवरण',
    'Upload Evidence': 'सबूत अपलोड करें',
    'Submit for Verification': 'सत्यापन के लिए जमा करें',
    'Carbon Credits Marketplace': 'कार्बन क्रेडिट बाज़ार',
    'Connect with global buyers and sellers in the carbon credit ecosystem': 'कार्बन क्रेडिट इकोसिस्टम में वैश्विक खरीदारों और विक्रेताओं से जुड़ें',
    'Avg. Price/Credit': 'औसत मूल्य/क्रेडिट',
    'Credits Available': 'उपलब्ध क्रेडिट',
    'Active Sellers': 'सक्रिय विक्रेता',
    'Active Buyers': 'सक्रिय खरीदार',
    'Available Credits': 'उपलब्ध क्रेडिट',
    'Buy Credits': 'क्रेडिट खरीदें',
    'View Details': 'विवरण देखें',
    'List Your Credits': 'अपने क्रेडिट सूचीबद्ध करें',
    'Start selling today': 'आज ही बेचना शुरू करें',
    'Price Alerts': 'मूल्य अलर्ट',
    'Get notified of price changes': 'मूल्य परिवर्तन की सूचना प्राप्त करें',
    'Market Trends': 'बाजार रुझान',
    'Enter address or coordinates': 'पता या निर्देशांक दर्ज करें',
    'Describe your environmental project in detail...': 'अपनी पर्यावरणीय परियोजना का विस्तार से वर्णन करें...',
    'Drop files here or click to browse': 'फ़ाइलें यहां छोड़ें या ब्राउज़ करने के लिए क्लिक करें',
    'Support: JPG, PNG, PDF, MP4 (max 10MB)': 'समर्थन: JPG, PNG, PDF, MP4 (अधिकतम 10MB)',
    'AI Verification Process': 'AI सत्यापन प्रक्रिया',
    'Data Collection': 'डेटा संग्रह',
    'Satellite imagery and project data analysis': 'सैटेलाइट इमेजरी और परियोजना डेटा विश्लेषण',
    'AI Analysis': 'AI विश्लेषण',
    'Machine learning algorithms verify impact': 'मशीन लर्निंग एल्गोरिदम प्रभाव सत्यापित करते हैं',
    'Blockchain Recording': 'ब्लॉकचेन रिकॉर्डिंग',
    'Results stored on immutable ledger': 'परिणाम अपरिवर्तनीय लेज़र पर संग्रहीत',
    'Credit Generation': 'क्रेडिट जनरेशन',
    'GramCredits issued based on verified impact': 'सत्यापित प्रभाव के आधार पर ग्रामक्रेडिट जारी किए गए',
    'Verification Benefits': 'सत्यापन लाभ',
    '95%+ accuracy with AI verification': 'AI सत्यापन के साथ 95%+ सटीकता',
    '24-48 hour verification time': '24-48 घंटे सत्यापन समय',
    'Transparent blockchain recording': 'पारदर्शी ब्लॉकचेन रिकॉर्डिंग',
    'Instant credit generation': 'तत्काल क्रेडिट जनरेशन',
    'Global marketplace access': 'वैश्विक बाज़ार पहुंच',
    'Real-time impact tracking': 'वास्तविक समय प्रभाव ट्रैकिंग',
    'Live Satellite Feed': 'लाइव सैटेलाइट फ़ीड',
    'Real-time satellite imagery of your project locations': 'आपकी परियोजना स्थानों की रियल-टाइम सैटेलाइट इमेजरी',
    'Environmental Metrics': 'पर्यावरणीय मेट्रिक्स',
    'Carbon Sequestration': 'कार्बन सीक्वेस्ट्रेशन',
    'Energy Generation': 'ऊर्जा उत्पादन',
    'Water Saved': 'पानी बचाया गया',
    'Soil Health': 'मिट्टी स्वास्थ्य',
    'Project Status': 'परियोजना स्थिति',
    'AI Insights': 'AI अंतर्दृष्टि',
    'Recommendation': 'सिफारिश',
    'Achievement': 'उपलब्धि',
    'lessons completed': 'पाठ पूरे किए गए',
    'credits available': 'उपलब्ध क्रेडिट',
    'per credit': 'प्रति क्रेडिट',
    'Search sellers, projects, or locations...': 'विक्रेताओं, परियोजनाओं या स्थानों को खोजें...',
    'Credits Earned': 'अर्जित क्रेडिट',
    'Type': 'प्रकार',
    'Confidence': 'आत्मविश्वास',
    'Register & Verify': 'पंजीकरण और सत्यापन',
    'Sign up and verify your farming activities through our AI system': 'साइन अप करें और हमारे AI सिस्टम के माध्यम से अपनी कृषि गतिविधियों को सत्यापित करें',
    'Take Climate Action': 'जलवायु कार्य करें',
    'Plant trees, adopt solar energy, or restore ecosystems': 'पेड़ लगाएं, सौर ऊर्जा अपनाएं, या पारिस्थितिकी तंत्र को बहाल करें',
    'Get Verified': 'सत्यापित हो जाएं',
    'AI and satellite technology verify your environmental impact': 'AI और सैटेलाइट तकनीक आपके पर्यावरणीय प्रभाव को सत्यापित करती है',
    'Earn Credits': 'क्रेडिट अर्जित करें',
    'Receive GramCredits and trade them in the global marketplace': 'ग्रामक्रेडिट प्राप्त करें और उन्हें वैश्विक बाज़ार में व्यापार करें',
    'Water Conservation': 'जल संरक्षण',
    'Soil Conservation': 'मिट्टी संरक्षण',
    'Waste Management': 'अपशिष्ट प्रबंधन',
    'Energy Efficiency': 'ऊर्जा दक्षता',
    'Introduction to Carbon Credits': 'कार्बन क्रेडिट का परिचय',
    'Learn the basics of carbon markets and how they work': 'कार्बन बाजारों की मूल बातें सीखें और वे कैसे काम करते हैं',
    'Sustainable Farming Practices': 'टिकाऊ कृषि प्रथाएं',
    'Modern techniques for eco-friendly agriculture': 'पर्यावरण-अनुकूल कृषि के लिए आधुनिक तकनीकें',
    'Renewable Energy Systems': 'नवीकरणीय ऊर्जा प्रणालियां',
    'Solar, wind, and biogas solutions for farmers': 'किसानों के लिए सौर, पवन और बायोगैस समाधान',
    'Water Conservation Techniques': 'जल संरक्षण तकनीकें',
    'Efficient irrigation and rainwater harvesting': 'कुशल सिंचाई और वर्षा जल संचयन',
    'Blockchain Fundamentals': 'ब्लॉकचेन मूल सिद्धांत',
    'Understanding blockchain technology for carbon credits': 'कार्बन क्रेडिट के लिए ब्लॉकचेन तकनीक को समझना',
    'Climate Change Adaptation': 'जलवायु परिवर्तन अनुकूलन',
    'Preparing your farm for climate resilience': 'जलवायु लचीलेपन के लिए अपने खेत को तैयार करना',
    'First Steps': 'पहले कदम',
    'Complete your first lesson': 'अपना पहला पाठ पूरा करें',
    'Knowledge Seeker': 'ज्ञान खोजी',
    'Complete 5 lessons': '5 पाठ पूरे करें',
    'Carbon Expert': 'कार्बन विशेषज्ञ',
    'Master carbon credit fundamentals': 'कार्बन क्रेडिट मूल सिद्धांतों में महारत हासिल करें',
    'Sustainable Farmer': 'टिकाऊ किसान',
    'Complete all farming courses': 'सभी कृषि पाठ्यक्रम पूरे करें',
    'Community Leader': 'सामुदायिक नेता',
    'Help 10 other farmers': '10 अन्य किसानों की मदद करें',
    'Green Pioneer': 'हरित अग्रणी',
    'Complete all courses': 'सभी कोर्स पूरे करें',
    'Total Labels': 'कुल लेबल',
    'Projects Completed': 'पूरी की गई परियोजनाएं',
    'Income Generated': 'उत्पन्न आय',
    'completed': 'पूरा हुआ',
    'Monthly Tree Planting': 'मासिक वृक्षारोपण',
    'Plant 1000 trees as a community': 'समुदाय के रूप में 1000 पेड़ लगाएं',
    'Solar Energy Drive': 'सौर ऊर्जा अभियान',
    'Install solar panels in 50 farms': '50 खेतों में सौर पैनल स्थापित करें',
    'Join Challenge': 'चुनौती में शामिल हों',
    'Voice Interface': 'आवाज इंटरफेस',
    'Press and hold to speak': 'बोलने के लिए दबाएं और रोकें',
    'Listening...': 'सुन रहा है...',
    'Processing...': 'प्रसंस्करण...',
    'Speak now': 'अब बोलें',
    'Voice command recognized': 'आवाज कमांड पहचाना गया',
    'Language changed to': 'भाषा बदली गई',
    'English': 'अंग्रेजी',
    'Hindi': 'हिंदी',
    'Telugu': 'तेलुगु',
    'Tamil': 'तमिल',
    'Bengali': 'बंगाली',
    'Gujarati': 'गुजराती',
    'Marathi': 'मराठी',
    'Punjabi': 'पंजाबी',
    'Kannada': 'कन्नड़',
    'Malayalam': 'मलयालम'
  },
  te: {
    // Navigation
    'Dashboard': 'డాష్‌బోర్డ్',
    'Marketplace': 'మార్కెట్‌ప్లేస్',
    'Verification': 'ధృవీకరణ',
    'Learning': 'నేర్చుకోవడం',
    'Login': 'లాగిన్',
    'Logout': 'లాగౌట్',
    
    // Homepage
    'Empowering Farmers': 'రైతులను శక్తివంతం చేయడం',
    'Protecting Planet': 'గ్రహాన్ని రక్షించడం',
    'Join thousands of farmers earning income from environmental conservation through AI-powered carbon credit verification and blockchain technology.': 'AI-శక్తితో కూడిన కార్బన్ క్రెడిట్ ధృవీకరణ మరియు బ్లాక్‌చెయిన్ టెక్నాలజీ ద్వారా పర్యావరణ పరిరక్షణ నుండి ఆదాయం పొందుతున్న వేలాది రైతులతో చేరండి.',
    'Start Earning Today': 'ఈరోజే సంపాదన ప్రారంభించండి',
    'Learn More': 'మరింత తెలుసుకోండి',
    'Revolutionary Features': 'విప్లవాత్మక లక్షణాలు',
    'Advanced technology made simple for farmers to participate in the global carbon economy': 'ప్రపంచ కార్బన్ ఆర్థిక వ్యవస్థలో పాల్గొనడానికి రైతుల కోసం అధునాతన సాంకేతికతను సరళంగా చేసింది',
    'How It Works': 'ఇది ఎలా పనిచేస్తుంది',
    'Simple steps to start earning from your environmental efforts': 'మీ పర్యావరణ ప్రయత్నాల నుండి సంపాదన ప్రారంభించడానికి సరళమైన దశలు',
    'Ready to Start Earning?': 'సంపాదన ప్రారంభించడానికి సిద్ధంగా ఉన్నారా?',
    'Join thousands of farmers making a difference and earning income': 'మార్పు తెచ్చి ఆదాయం పొందుతున్న వేలాది రైతులతో చేరండి',
    'Get Started Now': 'ఇప్పుడే ప్రారంభించండి',
    
    // Dashboard
    'Welcome back': 'తిరిగి స్వాగతం',
    'Track your environmental impact and earnings': 'మీ పర్యావరణ ప్రభావం మరియు ఆదాయాలను ట్రాక్ చేయండి',
    'Submit New Project': 'కొత్త ప్రాజెక్ట్ సమర్పించండి',
    'Record environmental actions': 'పర్యావరణ చర్యలను రికార్డ్ చేయండి',
    'List Credits for Sale': 'అమ్మకానికి క్రెడిట్లను జాబితా చేయండి',
    'Sell in marketplace': 'మార్కెట్‌ప్లేస్‌లో అమ్మండి',
    'Learn & Earn': 'నేర్చుకోండి మరియు సంపాదించండి',
    'Complete training modules': 'శిక్షణ మాడ్యూల్స్ పూర్తి చేయండి',
    'Total Credits Earned': 'మొత్తం సంపాదించిన క్రెడిట్లు',
    'Total Earnings': 'మొత్తం ఆదాయాలు',
    'Carbon Impact': 'కార్బన్ ప్రభావం',
    'Verification Score': 'ధృవీకరణ స్కోర్',
    'Recent Projects': 'ఇటీవలి ప్రాజెక్ట్లు',
    'Recent Transactions': 'ఇటీవలి లావాదేవీలు',
    'Environmental Impact': 'పర్యావరణ ప్రభావం',
    'Trees Equivalent': 'చెట్లకు సమానం',
    'Clean Energy': 'స్వచ్ఛమైన శక్తి',
    'People Inspired': 'ప్రేరేపించబడిన వ్యక్తులు',
    
    // Common
    'credits': 'క్రెడిట్లు',
    'GramCredits': 'గ్రామ్‌క్రెడిట్లు',
    'INR': 'రూపాయలు',
    'CO2 Tons Saved': 'CO2 టన్నులు ఆదా చేయబడింది',
    'Accuracy': 'ఖచ్చితత్వం',
    'verified': 'ధృవీకరించబడింది',
    'pending': 'పెండింగ్',
    'rejected': 'తిరస్కరించబడింది',
    'Verified': 'ధృవీకరించబడింది',
    'Beginner': 'ప్రారంభకుడు',
    'Intermediate': 'మధ్యస్థ',
    'Advanced': 'అధునాతన',
    'All Categories': 'అన్ని వర్గాలు',
    'Renewable Energy': 'పునరుత్పాదక శక్తి',
    'Forestry': 'అటవీ శాఖ',
    'Agriculture': 'వ్యవసాయం',
    'Conservation': 'పరిరక్షణ',
    'All Prices': 'అన్ని ధరలు',
    'Filter': 'ఫిల్టర్',
    'Save': 'సేవ్ చేయండి',
    'Edit': 'సవరించండి',
    'Full Name': 'పూర్తి పేరు',
    'Email': 'ఇమెయిల్',
    'Phone Number': 'ఫోన్ నంబర్',
    'Location': 'స్థానం',
    'Farm Size': 'వ్యవసాయ భూమి పరిమాణం',
    'Preferred Language': 'ప్రాధాన్య భాష',
    'Bio': 'జీవిత చరిత్ర',
    'Profile Information': 'ప్రొఫైల్ సమాచారం',
    'Achievements': 'విజయాలు',
    'Performance Stats': 'పనితీరు గణాంకాలు',
    'Quick Actions': 'త్వరిత చర్యలు',
    'View Analytics': 'విశ్లేషణలను చూడండి',
    'Share Profile': 'ప్రొఫైల్ భాగస్వామ్యం చేయండి',
    'View Certificates': 'సర్టిఫికేట్లను చూడండి',
    'WhatsApp Integration': 'WhatsApp ఏకీకరణ',
    'Get updates and notifications directly on WhatsApp': 'WhatsApp లో నేరుగా అప్‌డేట్లు మరియు నోటిఫికేషన్లను పొందండి',
    'Connected': 'కనెక్ట్ చేయబడింది',
    'Number': 'నంబర్',
    'Learning Hub': 'లెర్నింగ్ హబ్',
    'Learn, earn, and grow with our gamified green literacy platform': 'మా గేమిఫైడ్ గ్రీన్ లిటరసీ ప్లాట్‌ఫారమ్‌తో నేర్చుకోండి, సంపాదించండి మరియు ఎదగండి',
    'Lessons Completed': 'పూర్తి చేసిన పాఠాలు',
    'Points Earned': 'సంపాదించిన పాయింట్లు',
    'Badges Earned': 'సంపాదించిన బ్యాడ్జ్‌లు',
    'Courses Completed': 'పూర్తి చేసిన కోర్సులు',
    'Courses': 'కోర్సులు',
    'Achievements': 'విజయాలు',
    'Leaderboard': 'లీడర్‌బోర్డ్',
    'points': 'పాయింట్లు',
    'Start Course': 'కోర్సు ప్రారంభించండి',
    'Continue': 'కొనసాగించండి',
    'Download Certificate': 'సర్టిఫికేట్ డౌన్‌లోడ్ చేయండి',
    'Complete Next Lesson': 'తదుపరి పాఠం పూర్తి చేయండి',
    'Complete Course': 'కోర్సు పూర్తి చేయండి',
    'Community Challenges': 'కమ్యూనిటీ సవాళ్లు',
    'Recent Activity': 'ఇటీవలి కార్యకలాపం',
    'Project Verification': 'ప్రాజెక్ట్ ధృవీకరణ',
    'Submit your environmental projects for AI-powered verification': 'AI-శక్తితో కూడిన ధృవీకరణ కోసం మీ పర్యావరణ ప్రాజెక్ట్లను సమర్పించండి',
    'Submit Project': 'ప్రాజెక్ట్ సమర్పించండి',
    'Verification History': 'ధృవీకరణ చరిత్ర',
    'Real-time Monitoring': 'రియల్-టైమ్ మానిటరింగ్',
    'Project Title': 'ప్రాజెక్ట్ శీర్షిక',
    'Project Type': 'ప్రాజెక్ట్ రకం',
    'Select Project Type': 'ప్రాజెక్ట్ రకాన్ని ఎంచుకోండి',
    'Project Location': 'ప్రాజెక్ట్ స్థానం',
    'Project Description': 'ప్రాజెక్ట్ వివరణ',
    'Upload Evidence': 'సాక్ష్యం అప్‌లోడ్ చేయండి',
    'Submit for Verification': 'ధృవీకరణ కోసం సమర్పించండి',
    'Carbon Credits Marketplace': 'కార్బన్ క్రెడిట్స్ మార్కెట్‌ప్లేస్',
    'Connect with global buyers and sellers in the carbon credit ecosystem': 'కార్బన్ క్రెడిట్ ఎకోసిస్టమ్‌లో ప్రపంచ కొనుగోలుదారులు మరియు అమ్మకందారులతో కనెక్ట్ అవ్వండి',
    'Avg. Price/Credit': 'సగటు ధర/క్రెడిట్',
    'Credits Available': 'అందుబాటులో ఉన్న క్రెడిట్లు',
    'Active Sellers': 'క్రియాశీల అమ్మకందారులు',
    'Active Buyers': 'క్రియాశీల కొనుగోలుదారులు',
    'Available Credits': 'అందుబాటులో ఉన్న క్రెడిట్లు',
    'Buy Credits': 'క్రెడిట్లను కొనుగోలు చేయండి',
    'View Details': 'వివరాలను చూడండి',
    'List Your Credits': 'మీ క్రెడిట్లను జాబితా చేయండి',
    'Start selling today': 'ఈరోజే అమ్మకం ప్రారంభించండి',
    'Price Alerts': 'ధర హెచ్చరికలు',
    'Get notified of price changes': 'ధర మార్పుల గురించి తెలియజేయబడండి',
    'Market Trends': 'మార్కెట్ ట్రెండ్స్',
    'Enter address or coordinates': 'చిరునామా లేదా కోఆర్డినేట్లను నమోదు చేయండి',
    'Describe your environmental project in detail...': 'మీ పర్యావరణ ప్రాజెక్ట్‌ను వివరంగా వర్ణించండి...',
    'Drop files here or click to browse': 'ఫైల్‌లను ఇక్కడ వదలండి లేదా బ్రౌజ్ చేయడానికి క్లిక్ చేయండి',
    'Support: JPG, PNG, PDF, MP4 (max 10MB)': 'మద్దతు: JPG, PNG, PDF, MP4 (గరిష్టం 10MB)',
    'AI Verification Process': 'AI ధృవీకరణ ప్రక్రియ',
    'Data Collection': 'డేటా సేకరణ',
    'Satellite imagery and project data analysis': 'ఉపగ్రహ చిత్రాలు మరియు ప్రాజెక్ట్ డేటా విశ్లేషణ',
    'AI Analysis': 'AI విశ్లేషణ',
    'Machine learning algorithms verify impact': 'మెషిన్ లెర్నింగ్ అల్గోరిథమ్‌లు ప్రభావాన్ని ధృవీకరిస్తాయి',
    'Blockchain Recording': 'బ్లాక్‌చెయిన్ రికార్డింగ్',
    'Results stored on immutable ledger': 'ఫలితాలు మార్చలేని లెడ్జర్‌లో నిల్వ చేయబడతాయి',
    'Credit Generation': 'క్రెడిట్ జనరేషన్',
    'GramCredits issued based on verified impact': 'ధృవీకరించబడిన ప్రభావం ఆధారంగా గ్రామ్‌క్రెడిట్లు జారీ చేయబడతాయి',
    'Verification Benefits': 'ధృవీకరణ ప్రయోజనాలు',
    '95%+ accuracy with AI verification': 'AI ధృవీకరణతో 95%+ ఖచ్చితత్వం',
    '24-48 hour verification time': '24-48 గంటల ధృవీకరణ సమయం',
    'Transparent blockchain recording': 'పారదర్శక బ్లాక్‌చెయిన్ రికార్డింగ్',
    'Instant credit generation': 'తక్షణ క్రెడిట్ జనరేషన్',
    'Global marketplace access': 'ప్రపంచ మార్కెట్‌ప్లేస్ యాక్సెస్',
    'Real-time impact tracking': 'రియల్-టైమ్ ప్రభావ ట్రాకింగ్',
    'Live Satellite Feed': 'లైవ్ సాటిలైట్ ఫీడ్',
    'Real-time satellite imagery of your project locations': 'మీ ప్రాజెక్ట్ స్థానాల రియల్-టైమ్ ఉపగ్రహ చిత్రాలు',
    'Environmental Metrics': 'పర్యావరణ మెట్రిక్స్',
    'Carbon Sequestration': 'కార్బన్ సీక్వెస్ట్రేషన్',
    'Energy Generation': 'శక్తి ఉత్పత్తి',
    'Water Saved': 'నీరు ఆదా చేయబడింది',
    'Soil Health': 'మట్టి ఆరోగ్యం',
    'Project Status': 'ప్రాజెక్ట్ స్థితి',
    'AI Insights': 'AI అంతర్దృష్టులు',
    'Recommendation': 'సిఫార్సు',
    'Achievement': 'విజయం',
    'lessons completed': 'పూర్తి చేసిన పాఠాలు',
    'credits available': 'అందుబాటులో ఉన్న క్రెడిట్లు',
    'per credit': 'ప్రతి క్రెడిట్‌కు',
    'Search sellers, projects, or locations...': 'అమ్మకందారులు, ప్రాజెక్ట్లు లేదా స్థానాలను వెతకండి...',
    'Credits Earned': 'సంపాదించిన క్రెడిట్లు',
    'Type': 'రకం',
    'Confidence': 'విశ్వాసం',
    'Register & Verify': 'నమోదు మరియు ధృవీకరణ',
    'Sign up and verify your farming activities through our AI system': 'మా AI సిస్టమ్ ద్వారా మీ వ్యవసాయ కార్యకలాపాలను సైన్ అప్ చేసి ధృవీకరించండి',
    'Take Climate Action': 'వాతావరణ చర్య తీసుకోండి',
    'Plant trees, adopt solar energy, or restore ecosystems': 'చెట్లను నాటండి, సౌర శక్తిని అవలంబించండి లేదా పర్యావరణ వ్యవస్థలను పునరుద్ధరించండి',
    'Get Verified': 'ధృవీకరించబడండి',
    'AI and satellite technology verify your environmental impact': 'AI మరియు ఉపగ్రహ సాంకేతికత మీ పర్యావరణ ప్రభావాన్ని ధృవీకరిస్తుంది',
    'Earn Credits': 'క్రెడిట్లను సంపాదించండి',
    'Receive GramCredits and trade them in the global marketplace': 'గ్రామ్‌క్రెడిట్లను స్వీకరించండి మరియు వాటిని ప్రపంచ మార్కెట్‌ప్లేస్‌లో వ్యాపారం చేయండి',
    'Water Conservation': 'నీటి పరిరక్షణ',
    'Soil Conservation': 'మట్టి పరిరక్షణ',
    'Waste Management': 'వ్యర్థ పదార్థాల నిర్వహణ',
    'Energy Efficiency': 'శక్తి సామర్థ్యం',
    'Introduction to Carbon Credits': 'కార్బన్ క్రెడిట్లకు పరిచయం',
    'Learn the basics of carbon markets and how they work': 'కార్బన్ మార్కెట్ల ప్రాథమిక విషయాలు మరియు అవి ఎలా పనిచేస్తాయో నేర్చుకోండి',
    'Sustainable Farming Practices': 'స్థిరమైన వ్యవసాయ పద్ధతులు',
    'Modern techniques for eco-friendly agriculture': 'పర్యావరణ అనుకూల వ్యవసాయం కోసం ఆధునిక పద్ధతులు',
    'Renewable Energy Systems': 'పునరుత్పాదక శక్తి వ్యవస్థలు',
    'Solar, wind, and biogas solutions for farmers': 'రైతుల కోసం సౌర, గాలి మరియు బయోగ్యాస్ పరిష్కారాలు',
    'Water Conservation Techniques': 'నీటి పరిరక్షణ పద్ధతులు',
    'Efficient irrigation and rainwater harvesting': 'సమర్థవంతమైన నీటిపారుదల మరియు వర్షపు నీటి సేకరణ',
    'Blockchain Fundamentals': 'బ్లాక్‌చెయిన్ ప్రాథమిక అంశాలు',
    'Understanding blockchain technology for carbon credits': 'కార్బన్ క్రెడిట్ల కోసం బ్లాక్‌చెయిన్ సాంకేతికతను అర్థం చేసుకోవడం',
    'Climate Change Adaptation': 'వాతావరణ మార్పు అనుకూలత',
    'Preparing your farm for climate resilience': 'వాతావరణ స్థితిస్థాపకత కోసం మీ వ్యవసాయ భూమిని సిద్ధం చేయడం',
    'First Steps': 'మొదటి దశలు',
    'Complete your first lesson': 'మీ మొదటి పాఠాన్ని పూర్తి చేయండి',
    'Knowledge Seeker': 'జ్ఞాన అన్వేషకుడు',
    'Complete 5 lessons': '5 పాఠాలను పూర్తి చేయండి',
    'Carbon Expert': 'కార్బన్ నిపుణుడు',
    'Master carbon credit fundamentals': 'కార్బన్ క్రెడిట్ ప్రాథమిక అంశాలలో నైపుణ్యం పొందండి',
    'Sustainable Farmer': 'స్థిరమైన రైతు',
    'Complete all farming courses': 'అన్ని వ్యవసాయ కోర్సులను పూర్తి చేయండి',
    'Community Leader': 'కమ్యూనిటీ లీడర్',
    'Help 10 other farmers': '10 ఇతర రైతులకు సహాయం చేయండి',
    'Green Pioneer': 'గ్రీన్ పయనీర్',
    'Complete all courses': 'అన్ని కోర్సులను పూర్తి చేయండి',
    'Total Labels': 'మొత్తం లేబుల్స్',
    'Projects Completed': 'పూర్తి చేసిన ప్రాజెక్ట్లు',
    'Income Generated': 'ఉత్పన్నమైన ఆదాయం',
    'completed': 'పూర్తయింది',
    'Monthly Tree Planting': 'నెలవారీ చెట్ల నాటడం',
    'Plant 1000 trees as a community': 'కమ్యూనిటీగా 1000 చెట్లను నాటండి',
    'Solar Energy Drive': 'సౌర శక్తి ప్రచారం',
    'Install solar panels in 50 farms': '50 వ్యవసాయ భూములలో సౌర ప్యానెల్లను ఏర్పాటు చేయండి',
    'Join Challenge': 'సవాలులో చేరండి',
    'Voice Interface': 'వాయిస్ ఇంటర్‌ఫేస్',
    'Press and hold to speak': 'మాట్లాడటానికి నొక్కి పట్టుకోండి',
    'Listening...': 'వింటున్నాను...',
    'Processing...': 'ప్రాసెసింగ్...',
    'Speak now': 'ఇప్పుడు మాట్లాడండి',
    'Voice command recognized': 'వాయిస్ కమాండ్ గుర్తించబడింది',
    'Language changed to': 'భాష మార్చబడింది',
    'English': 'ఇంగ్లీష్',
    'Hindi': 'హిందీ',
    'Telugu': 'తెలుగు',
    'Tamil': 'తమిళం',
    'Bengali': 'బెంగాలీ',
    'Gujarati': 'గుజరాతీ',
    'Marathi': 'మరాఠీ',
    'Punjabi': 'పంజాబీ',
    'Kannada': 'కన్నడ',
    'Malayalam': 'మలయాళం'
  },
  ta: {
    // Navigation
    'Dashboard': 'டாஷ்போர்டு',
    'Marketplace': 'சந்தை',
    'Verification': 'சரிபார்ப்பு',
    'Learning': 'கற்றல்',
    'Login': 'உள்நுழைவு',
    'Logout': 'வெளியேறு',
    
    // Homepage
    'Empowering Farmers': 'விவசாயிகளை வலுப்படுத்துதல்',
    'Protecting Planet': 'கிரகத்தைப் பாதுகாத்தல்',
    'Join thousands of farmers earning income from environmental conservation through AI-powered carbon credit verification and blockchain technology.': 'AI-இயங்கும் கார்பன் கிரெடிட் சரிபார்ப்பு மற்றும் பிளாக்செயின் தொழில்நுட்பம் மூலம் சுற்றுச்சூழல் பாதுகாப்பிலிருந்து வருமானம் ஈட்டும் ஆயிரக்கணக்கான விவசாயிகளுடன் சேரவும்.',
    'Start Earning Today': 'இன்றே சம்பாதிக்க ஆரம்பிக்கவும்',
    'Learn More': 'மேலும் அறிக',
    'Revolutionary Features': 'புரட்சிகர அம்சங்கள்',
    'Advanced technology made simple for farmers to participate in the global carbon economy': 'உலகளாவிய கார்பன் பொருளாதாரத்தில் பங்கேற்க விவசாயிகளுக்கு மேம்பட்ட தொழில்நுட்பம் எளிமையாக்கப்பட்டது',
    'How It Works': 'இது எவ்வாறு செயல்படுகிறது',
    'Simple steps to start earning from your environmental efforts': 'உங்கள் சுற்றுச்சூழல் முயற்சிகளிலிருந்து சம்பாதிக்க ஆரம்பிக்க எளிய படிகள்',
    'Ready to Start Earning?': 'சம்பாதிக்க ஆரம்பிக்க தயாரா?',
    'Join thousands of farmers making a difference and earning income': 'மாற்றத்தை ஏற்படுத்தி வருமானம் ஈட்டும் ஆயிரக்கணக்கான விவசாயிகளுடன் சேரவும்',
    'Get Started Now': 'இப்போதே ஆரம்பிக்கவும்',
    
    // Dashboard
    'Welcome back': 'மீண்டும் வரவேற்கிறோம்',
    'Track your environmental impact and earnings': 'உங்கள் சுற்றுச்சூழல் தாக்கம் மற்றும் வருவாயைக் கண்காணிக்கவும்',
    'Submit New Project': 'புதிய திட்டத்தை சமர்ப்பிக்கவும்',
    'Record environmental actions': 'சுற்றுச்சூழல் நடவடிக்கைகளை பதிவு செய்யவும்',
    'List Credits for Sale': 'விற்பனைக்கு கிரெடிட்களை பட்டியலிடவும்',
    'Sell in marketplace': 'சந்தையில் விற்கவும்',
    'Learn & Earn': 'கற்று சம்பாதிக்கவும்',
    'Complete training modules': 'பயிற்சி தொகுதிகளை முடிக்கவும்',
    'Total Credits Earned': 'மொத்த சம்பாதித்த கிரெடிட்கள்',
    'Total Earnings': 'மொத்த வருவாய்',
    'Carbon Impact': 'கார்பன் தாக்கம்',
    'Verification Score': 'சரிபார்ப்பு மதிப்பெண்',
    'Recent Projects': 'சமீபத்திய திட்டங்கள்',
    'Recent Transactions': 'சமீபத்திய பரிவர்த்தனைகள்',
    'Environmental Impact': 'சுற்றுச்சூழல் தாக்கம்',
    'Trees Equivalent': 'மரங்களுக்கு சமமானது',
    'Clean Energy': 'சுத்தமான ஆற்றல்',
    'People Inspired': 'ஊக்கமளித்த மக்கள்',
    
    // Common
    'credits': 'கிரெடிட்கள்',
    'GramCredits': 'கிராம்கிரெடிட்கள்',
    'INR': 'ரூபாய்',
    'CO2 Tons Saved': 'CO2 டன்கள் சேமிக்கப்பட்டது',
    'Accuracy': 'துல்லியம்',
    'verified': 'சரிபார்க்கப்பட்டது',
    'pending': 'நிலுவையில்',
    'rejected': 'நிராகரிக்கப்பட்டது',
    'Verified': 'சரிபார்க்கப்பட்டது',
    'Beginner': 'ஆரம்பநிலை',
    'Intermediate': 'இடைநிலை',
    'Advanced': 'மேம்பட்ட',
    'All Categories': 'அனைத்து வகைகள்',
    'Renewable Energy': 'புதுப்பிக்கத்தக்க ஆற்றல்',
    'Forestry': 'வனவியல்',
    'Agriculture': 'விவசாயம்',
    'Conservation': 'பாதுகாப்பு',
    'All Prices': 'அனைத்து விலைகள்',
    'Filter': 'வடிகட்டி',
    'Save': 'சேமிக்கவும்',
    'Edit': 'திருத்தவும்',
    'Full Name': 'முழு பெயர்',
    'Email': 'மின்னஞ்சல்',
    'Phone Number': 'தொலைபேசி எண்',
    'Location': 'இடம்',
    'Farm Size': 'பண்ணை அளவு',
    'Preferred Language': 'விருப்பமான மொழி',
    'Bio': 'வாழ்க்கை வரலாறு',
    'Profile Information': 'சுயவிவர தகவல்',
    'Achievements': 'சாதனைகள்',
    'Performance Stats': 'செயல்திறன் புள்ளிவிவரங்கள்',
    'Quick Actions': 'விரைவு நடவடிக்கைகள்',
    'View Analytics': 'பகுப்பாய்வுகளைப் பார்க்கவும்',
    'Share Profile': 'சுயவிவரத்தைப் பகிரவும்',
    'View Certificates': 'சான்றிதழ்களைப் பார்க்கவும்',
    'WhatsApp Integration': 'WhatsApp ஒருங்கிணைப்பு',
    'Get updates and notifications directly on WhatsApp': 'WhatsApp இல் நேரடியாக புதுப்பிப்புகள் மற்றும் அறிவிப்புகளைப் பெறவும்',
    'Connected': 'இணைக்கப்பட்டது',
    'Number': 'எண்',
    'Learning Hub': 'கற்றல் மையம்',
    'Learn, earn, and grow with our gamified green literacy platform': 'எங்கள் கேமிஃபைட் பசுமை கல்வியறிவு தளத்துடன் கற்றுக்கொள்ளுங்கள், சம்பாதியுங்கள் மற்றும் வளருங்கள்',
    'Lessons Completed': 'முடிக்கப்பட்ட பாடங்கள்',
    'Points Earned': 'சம்பாதித்த புள்ளிகள்',
    'Badges Earned': 'சம்பாதித்த பேட்ஜ்கள்',
    'Courses Completed': 'முடிக்கப்பட்ட பாடநெறிகள்',
    'Courses': 'பாடநெறிகள்',
    'Achievements': 'சாதனைகள்',
    'Leaderboard': 'தலைமை பலகை',
    'points': 'புள்ளிகள்',
    'Start Course': 'பாடநெறியைத் தொடங்கவும்',
    'Continue': 'தொடரவும்',
    'Download Certificate': 'சான்றிதழைப் பதிவிறக்கவும்',
    'Complete Next Lesson': 'அடுத்த பாடத்தை முடிக்கவும்',
    'Complete Course': 'பாடநெறியை முடிக்கவும்',
    'Community Challenges': 'சமூக சவால்கள்',
    'Recent Activity': 'சமீபத்திய செயல்பாடு',
    'Project Verification': 'திட்ட சரிபார்ப்பு',
    'Submit your environmental projects for AI-powered verification': 'AI-இயங்கும் சரிபார்ப்புக்காக உங்கள் சுற்றுச்சூழல் திட்டங்களைச் சமர்ப்பிக்கவும்',
    'Submit Project': 'திட்டத்தைச் சமர்ப்பிக்கவும்',
    'Verification History': 'சரிபார்ப்பு வரலாறு',
    'Real-time Monitoring': 'நிகழ்நேர கண்காணிப்பு',
    'Project Title': 'திட்ட தலைப்பு',
    'Project Type': 'திட்ட வகை',
    'Select Project Type': 'திட்ட வகையைத் தேர்ந்தெடுக்கவும்',
    'Project Location': 'திட்ட இடம்',
    'Project Description': 'திட்ட விளக்கம்',
    'Upload Evidence': 'ஆதாரத்தைப் பதிவேற்றவும்',
    'Submit for Verification': 'சரிபார்ப்புக்காக சமர்ப்பிக்கவும்',
    'Carbon Credits Marketplace': 'கார்பன் கிரெடிட்கள் சந்தை',
    'Connect with global buyers and sellers in the carbon credit ecosystem': 'கார்பன் கிரெடிட் சுற்றுச்சூழல் அமைப்பில் உலகளாவிய வாங்குபவர்கள் மற்றும் விற்பனையாளர்களுடன் இணைக்கவும்',
    'Avg. Price/Credit': 'சராசரி விலை/கிரெடிட்',
    'Credits Available': 'கிடைக்கும் கிரெடிட்கள்',
    'Active Sellers': 'செயலில் உள்ள விற்பனையாளர்கள்',
    'Active Buyers': 'செயலில் உள்ள வாங்குபவர்கள்',
    'Available Credits': 'கிடைக்கும் கிரெடிட்கள்',
    'Buy Credits': 'கிரெடிட்களை வாங்கவும்',
    'View Details': 'விவரங்களைப் பார்க்கவும்',
    'List Your Credits': 'உங்கள் கிரெடிட்களைப் பட்டியலிடவும்',
    'Start selling today': 'இன்றே விற்பனையைத் தொடங்கவும்',
    'Price Alerts': 'விலை எச்சரிக்கைகள்',
    'Get notified of price changes': 'விலை மாற்றங்களைப் பற்றி அறிவிக்கப்படுங்கள்',
    'Market Trends': 'சந்தை போக்குகள்',
    'Enter address or coordinates': 'முகவரி அல்லது ஆயத்தொலைவுகளை உள்ளிடவும்',
    'Describe your environmental project in detail...': 'உங்கள் சுற்றுச்சூழல் திட்டத்தை விரிவாக விவரிக்கவும்...',
    'Drop files here or click to browse': 'கோப்புகளை இங்கே விடவும் அல்லது உலாவ கிளிக் செய்யவும்',
    'Support: JPG, PNG, PDF, MP4 (max 10MB)': 'ஆதரவு: JPG, PNG, PDF, MP4 (அதிகபட்சம் 10MB)',
    'AI Verification Process': 'AI சரிபார்ப்பு செயல்முறை',
    'Data Collection': 'தரவு சேகரிப்பு',
    'Satellite imagery and project data analysis': 'செயற்கைக்கோள் படங்கள் மற்றும் திட்ட தரவு பகுப்பாய்வு',
    'AI Analysis': 'AI பகுப்பாய்வு',
    'Machine learning algorithms verify impact': 'இயந்திர கற்றல் வழிமுறைகள் தாக்கத்தைச் சரிபார்க்கின்றன',
    'Blockchain Recording': 'பிளாக்செயின் பதிவு',
    'Results stored on immutable ledger': 'முடிவுகள் மாற்ற முடியாத லெட்ஜரில் சேமிக்கப்படுகின்றன',
    'Credit Generation': 'கிரெடிட் உருவாக்கம்',
    'GramCredits issued based on verified impact': 'சரிபார்க்கப்பட்ட தாக்கத்தின் அடிப்படையில் கிராம்கிரெடிட்கள் வழங்கப்படுகின்றன',
    'Verification Benefits': 'சரிபார்ப்பு நன்மைகள்',
    '95%+ accuracy with AI verification': 'AI சரிபார்ப்புடன் 95%+ துல்லியம்',
    '24-48 hour verification time': '24-48 மணிநேர சரிபார்ப்பு நேரம்',
    'Transparent blockchain recording': 'வெளிப்படையான பிளாக்செயின் பதிவு',
    'Instant credit generation': 'உடனடி கிரெடிட் உருவாக்கம்',
    'Global marketplace access': 'உலகளாவிய சந்தை அணுகல்',
    'Real-time impact tracking': 'நிகழ்நேர தாக்க கண்காணிப்பு',
    'Live Satellite Feed': 'நேரடி செயற்கைக்கோள் ஊட்டம்',
    'Real-time satellite imagery of your project locations': 'உங்கள் திட்ட இடங்களின் நிகழ்நேர செயற்கைக்கோள் படங்கள்',
    'Environmental Metrics': 'சுற்றுச்சூழல் அளவீடுகள்',
    'Carbon Sequestration': 'கார்பன் வரிசைப்படுத்தல்',
    'Energy Generation': 'ஆற்றல் உருவாக்கம்',
    'Water Saved': 'நீர் சேமிக்கப்பட்டது',
    'Soil Health': 'மண் ஆரோக்கியம்',
    'Project Status': 'திட்ட நிலை',
    'AI Insights': 'AI நுண்ணறிவுகள்',
    'Recommendation': 'பரிந்துரை',
    'Achievement': 'சாதனை',
    'lessons completed': 'முடிக்கப்பட்ட பாடங்கள்',
    'credits available': 'கிடைக்கும் கிரெடிட்கள்',
    'per credit': 'ஒரு கிரெடிட்டுக்கு',
    'Search sellers, projects, or locations...': 'விற்பனையாளர்கள், திட்டங்கள் அல்லது இடங்களைத் தேடவும்...',
    'Credits Earned': 'சம்பாதித்த கிரெடிட்கள்',
    'Type': 'வகை',
    'Confidence': 'நம்பிக்கை',
    'Register & Verify': 'பதிவு மற்றும் சரிபார்ப்பு',
    'Sign up and verify your farming activities through our AI system': 'எங்கள் AI அமைப்பு மூலம் உங்கள் விவசாய நடவடிக்கைகளைப் பதிவு செய்து சரிபார்க்கவும்',
    'Take Climate Action': 'காலநிலை நடவடிக்கை எடுக்கவும்',
    'Plant trees, adopt solar energy, or restore ecosystems': 'மரங்களை நடவும், சூரிய ஆற்றலை ஏற்றுக்கொள்ளுங்கள் அல்லது சுற்றுச்சூழல் அமைப்புகளை மீட்டெடுக்கவும்',
    'Get Verified': 'சரிபார்க்கப்படுங்கள்',
    'AI and satellite technology verify your environmental impact': 'AI மற்றும் செயற்கைக்கோள் தொழில்நுட்பம் உங்கள் சுற்றுச்சூழல் தாக்கத்தைச் சரிபார்க்கிறது',
    'Earn Credits': 'கிரெடிட்களைச் சம்பாதிக்கவும்',
    'Receive GramCredits and trade them in the global marketplace': 'கிராம்கிரெடிட்களைப் பெற்று உலகளாவிய சந்தையில் வர்த்தகம் செய்யுங்கள்',
    'Water Conservation': 'நீர் பாதுகாப்பு',
    'Soil Conservation': 'மண் பாதுகாப்பு',
    'Waste Management': 'கழிவு மேலாண்மை',
    'Energy Efficiency': 'ஆற்றல் திறன்',
    'Introduction to Carbon Credits': 'கார்பன் கிரெடிட்களுக்கான அறிமுகம்',
    'Learn the basics of carbon markets and how they work': 'கார்பன் சந்தைகளின் அடிப்படைகள் மற்றும் அவை எவ்வாறு செயல்படுகின்றன என்பதைக் கற்றுக்கொள்ளுங்கள்',
    'Sustainable Farming Practices': 'நிலையான விவசாய நடைமுறைகள்',
    'Modern techniques for eco-friendly agriculture': 'சுற்றுச்சூழல் நட்பு விவசாயத்திற்கான நவீன நுட்பங்கள்',
    'Renewable Energy Systems': 'புதுப்பிக்கத்தக்க ஆற்றல் அமைப்புகள்',
    'Solar, wind, and biogas solutions for farmers': 'விவசாயிகளுக்கான சூரிய, காற்று மற்றும் உயிர்வாயு தீர்வுகள்',
    'Water Conservation Techniques': 'நீர் பாதுகாப்பு நுட்பங்கள்',
    'Efficient irrigation and rainwater harvesting': 'திறமையான நீர்ப்பாசனம் மற்றும் மழைநீர் சேகரிப்பு',
    'Blockchain Fundamentals': 'பிளாக்செயின் அடிப்படைகள்',
    'Understanding blockchain technology for carbon credits': 'கார்பன் கிரெடிட்களுக்கான பிளாக்செயின் தொழில்நுட்பத்தைப் புரிந்துகொள்ளுதல்',
    'Climate Change Adaptation': 'காலநிலை மாற்ற தழுவல்',
    'Preparing your farm for climate resilience': 'காலநிலை நெகிழ்ச்சித்தன்மைக்காக உங்கள் பண்ணையைத் தயார்படுத்துதல்',
    'First Steps': 'முதல் படிகள்',
    'Complete your first lesson': 'உங்கள் முதல் பாடத்தை முடிக்கவும்',
    'Knowledge Seeker': 'அறிவு தேடுபவர்',
    'Complete 5 lessons': '5 பாடங்களை முடிக்கவும்',
    'Carbon Expert': 'கார்பன் நிபுணர்',
    'Master carbon credit fundamentals': 'கார்பன் கிரெடிட் அடிப்படைகளில் தேர்ச்சி பெறுங்கள்',
    'Sustainable Farmer': 'நிலையான விவசாயி',
    'Complete all farming courses': 'அனைத்து விவசாய பாடநெறிகளையும் முடிக்கவும்',
    'Community Leader': 'சமூகத் தலைவர்',
    'Help 10 other farmers': '10 பிற விவசாயிகளுக்கு உதவுங்கள்',
    'Green Pioneer': 'பசுமை முன்னோடி',
    'Complete all courses': 'அனைத்து பாடநெறிகளையும் முடிக்கவும்',
    'Total Labels': 'மொத்த லேபிள்கள்',
    'Projects Completed': 'முடிக்கப்பட்ட திட்டங்கள்',
    'Income Generated': 'உருவாக்கப்பட்ட வருமானம்',
    'completed': 'முடிக்கப்பட்டது',
    'Monthly Tree Planting': 'மாதாந்திர மரம் நடுதல்',
    'Plant 1000 trees as a community': 'ஒரு சமூகமாக 1000 மரங்களை நடவும்',
    'Solar Energy Drive': 'சூரிய ஆற்றல் இயக்கம்',
    'Install solar panels in 50 farms': '50 பண்ணைகளில் சூரிய பேனல்களை நிறுவவும்',
    'Join Challenge': 'சவாலில் சேரவும்',
    'Voice Interface': 'குரல் இடைமுகம்',
    'Press and hold to speak': 'பேச அழுத்திப் பிடிக்கவும்',
    'Listening...': 'கேட்கிறது...',
    'Processing...': 'செயலாக்கம்...',
    'Speak now': 'இப்போது பேசுங்கள்',
    'Voice command recognized': 'குரல் கட்டளை அங்கீகரிக்கப்பட்டது',
    'Language changed to': 'மொழி மாற்றப்பட்டது',
    'English': 'ஆங்கிலம்',
    'Hindi': 'இந்தி',
    'Telugu': 'தெலுங்கு',
    'Tamil': 'தமிழ்',
    'Bengali': 'வங்காளம்',
    'Gujarati': 'குஜராத்தி',
    'Marathi': 'மராத்தி',
    'Punjabi': 'பஞ்சாபி',
    'Kannada': 'கன்னடம்',
    'Malayalam': 'மலையாளம்'
  },
  bn: {
    // Navigation
    'Dashboard': 'ড্যাশবোর্ড',
    'Marketplace': 'বাজার',
    'Verification': 'যাচাইকরণ',
    'Learning': 'শেখা',
    'Login': 'লগইন',
    'Logout': 'লগআউট',
    
    // Homepage
    'Empowering Farmers': 'কৃষকদের ক্ষমতায়ন',
    'Protecting Planet': 'গ্রহ রক্ষা',
    'Join thousands of farmers earning income from environmental conservation through AI-powered carbon credit verification and blockchain technology.': 'AI-চালিত কার্বন ক্রেডিট যাচাইকরণ এবং ব্লকচেইন প্রযুক্তির মাধ্যমে পরিবেশ সংরক্ষণ থেকে আয় করা হাজার হাজার কৃষকের সাথে যোগ দিন।',
    'Start Earning Today': 'আজই আয় শুরু করুন',
    'Learn More': 'আরও জানুন',
    'Revolutionary Features': 'বিপ্লবী বৈশিষ্ট্য',
    'Advanced technology made simple for farmers to participate in the global carbon economy': 'বিশ্বব্যাপী কার্বন অর্থনীতিতে অংশগ্রহণের জন্য কৃষকদের জন্য উন্নত প্রযুক্তি সহজ করা হয়েছে',
    'How It Works': 'এটি কীভাবে কাজ করে',
    'Simple steps to start earning from your environmental efforts': 'আপনার পরিবেশগত প্রচেষ্টা থেকে আয় শুরু করার সহজ পদক্ষেপ',
    'Ready to Start Earning?': 'আয় শুরু করতে প্রস্তুত?',
    'Join thousands of farmers making a difference and earning income': 'পরিবর্তন আনতে এবং আয় করতে হাজার হাজার কৃষকের সাথে যোগ দিন',
    'Get Started Now': 'এখনই শুরু করুন',
    
    // Dashboard
    'Welcome back': 'ফিরে স্বাগতম',
    'Track your environmental impact and earnings': 'আপনার পরিবেশগত প্রভাব এবং আয় ট্র্যাক করুন',
    'Submit New Project': 'নতুন প্রকল্প জমা দিন',
    'Record environmental actions': 'পরিবেশগত কর্ম রেকর্ড করুন',
    'List Credits for Sale': 'বিক্রয়ের জন্য ক্রেডিট তালিকা করুন',
    'Sell in marketplace': 'বাজারে বিক্রি করুন',
    'Learn & Earn': 'শিখুন এবং আয় করুন',
    'Complete training modules': 'প্রশিক্ষণ মডিউল সম্পূর্ণ করুন',
    'Total Credits Earned': 'মোট অর্জিত ক্রেডিট',
    'Total Earnings': 'মোট আয়',
    'Carbon Impact': 'কার্বন প্রভাব',
    'Verification Score': 'যাচাইকরণ স্কোর',
    'Recent Projects': 'সাম্প্রতিক প্রকল্প',
    'Recent Transactions': 'সাম্প্রতিক লেনদেন',
    'Environmental Impact': 'পরিবেশগত প্রভাব',
    'Trees Equivalent': 'গাছের সমতুল্য',
    'Clean Energy': 'পরিচ্ছন্ন শক্তি',
    'People Inspired': 'অনুপ্রাণিত মানুষ',
    
    // Common
    'credits': 'ক্রেডিট',
    'GramCredits': 'গ্রামক্রেডিট',
    'INR': 'টাকা',
    'CO2 Tons Saved': 'CO2 টন সংরক্ষিত',
    'Accuracy': 'নির্ভুলতা',
    'verified': 'যাচাইকৃত',
    'pending': 'অপেক্ষমাণ',
    'rejected': 'প্রত্যাখ্যাত',
    'Verified': 'যাচাইকৃত',
    'Beginner': 'শিক্ষানবিস',
    'Intermediate': 'মধ্যবর্তী',
    'Advanced': 'উন্নত',
    'All Categories': 'সব বিভাগ',
    'Renewable Energy': 'নবায়নযোগ্য শক্তি',
    'Forestry': 'বনায়ন',
    'Agriculture': 'কৃষি',
    'Conservation': 'সংরক্ষণ',
    'All Prices': 'সব দাম',
    'Filter': 'ফিল্টার',
    'Save': 'সংরক্ষণ করুন',
    'Edit': 'সম্পাদনা করুন',
    'Full Name': 'পূর্ণ নাম',
    'Email': 'ইমেইল',
    'Phone Number': 'ফোন নম্বর',
    'Location': 'অবস্থান',
    'Farm Size': 'খামারের আকার',
    'Preferred Language': 'পছন্দের ভাষা',
    'Bio': 'জীবনী',
    'Profile Information': 'প্রোফাইল তথ্য',
    'Achievements': 'অর্জন',
    'Performance Stats': 'কর্মক্ষমতা পরিসংখ্যান',
    'Quick Actions': 'দ্রুত কর্ম',
    'View Analytics': 'বিশ্লেষণ দেখুন',
    'Share Profile': 'প্রোফাইল শেয়ার করুন',
    'View Certificates': 'সার্টিফিকেট দেখুন',
    'WhatsApp Integration': 'WhatsApp একীকরণ',
    'Get updates and notifications directly on WhatsApp': 'WhatsApp এ সরাসরি আপডেট এবং বিজ্ঞপ্তি পান',
    'Connected': 'সংযুক্ত',
    'Number': 'নম্বর',
    'Learning Hub': 'শেখার কেন্দ্র',
    'Learn, earn, and grow with our gamified green literacy platform': 'আমাদের গেমিফাইড গ্রিন লিটারেসি প্ল্যাটফর্মের সাথে শিখুন, আয় করুন এবং বৃদ্ধি করুন',
    'Lessons Completed': 'সম্পূর্ণ পাঠ',
    'Points Earned': 'অর্জিত পয়েন্ট',
    'Badges Earned': 'অর্জিত ব্যাজ',
    'Courses Completed': 'সম্পূর্ণ কোর্স',
    'Courses': 'কোর্স',
    'Achievements': 'অর্জন',
    'Leaderboard': 'লিডারবোর্ড',
    'points': 'পয়েন্ট',
    'Start Course': 'কোর্স শুরু করুন',
    'Continue': 'চালিয়ে যান',
    'Download Certificate': 'সার্টিফিকেট ডাউনলোড করুন',
    'Complete Next Lesson': 'পরবর্তী পাঠ সম্পূর্ণ করুন',
    'Complete Course': 'কোর্স সম্পূর্ণ করুন',
    'Community Challenges': 'কমিউনিটি চ্যালেঞ্জ',
    'Recent Activity': 'সাম্প্রতিক কার্যকলাপ',
    'Project Verification': 'প্রকল্প যাচাইকরণ',
    'Submit your environmental projects for AI-powered verification': 'AI-চালিত যাচাইকরণের জন্য আপনার পরিবেশগত প্রকল্প জমা দিন',
    'Submit Project': 'প্রকল্প জমা দিন',
    'Verification History': 'যাচাইকরণ ইতিহাস',
    'Real-time Monitoring': 'রিয়েল-টাইম মনিটরিং',
    'Project Title': 'প্রকল্পের শিরোনাম',
    'Project Type': 'প্রকল্পের ধরন',
    'Select Project Type': 'প্রকল্পের ধরন নির্বাচন করুন',
    'Project Location': 'প্রকল্পের অবস্থান',
    'Project Description': 'প্রকল্পের বিবরণ',
    'Upload Evidence': 'প্রমাণ আপলোড করুন',
    'Submit for Verification': 'যাচাইকরণের জন্য জমা দিন',
    'Carbon Credits Marketplace': 'কার্বন ক্রেডিট বাজার',
    'Connect with global buyers and sellers in the carbon credit ecosystem': 'কার্বন ক্রেডিট ইকোসিস্টেমে বিশ্বব্যাপী ক্রেতা এবং বিক্রেতাদের সাথে সংযোগ করুন',
    'Avg. Price/Credit': 'গড় দাম/ক্রেডিট',
    'Credits Available': 'উপলব্ধ ক্রেডিট',
    'Active Sellers': 'সক্রিয় বিক্রেতা',
    'Active Buyers': 'সক্রিয় ক্রেতা',
    'Available Credits': 'উপলব্ধ ক্রেডিট',
    'Buy Credits': 'ক্রেডিট কিনুন',
    'View Details': 'বিস্তারিত দেখুন',
    'List Your Credits': 'আপনার ক্রেডিট তালিকা করুন',
    'Start selling today': 'আজই বিক্রি শুরু করুন',
    'Price Alerts': 'দাম সতর্কতা',
    'Get notified of price changes': 'দাম পরিবর্তনের বিজ্ঞপ্তি পান',
    'Market Trends': 'বাজার প্রবণতা',
    'Enter address or coordinates': 'ঠিকানা বা স্থানাঙ্ক প্রবেশ করুন',
    'Describe your environmental project in detail...': 'আপনার পরিবেশগত প্রকল্প বিস্তারিতভাবে বর্ণনা করুন...',
    'Drop files here or click to browse': 'ফাইল এখানে ড্রপ করুন বা ব্রাউজ করতে ক্লিক করুন',
    'Support: JPG, PNG, PDF, MP4 (max 10MB)': 'সমর্থন: JPG, PNG, PDF, MP4 (সর্বোচ্চ 10MB)',
    'AI Verification Process': 'AI যাচাইকরণ প্রক্রিয়া',
    'Data Collection': 'ডেটা সংগ্রহ',
    'Satellite imagery and project data analysis': 'স্যাটেলাইট চিত্র এবং প্রকল্প ডেটা বিশ্লেষণ',
    'AI Analysis': 'AI বিশ্লেষণ',
    'Machine learning algorithms verify impact': 'মেশিন লার্নিং অ্যালগরিদম প্রভাব যাচাই করে',
    'Blockchain Recording': 'ব্লকচেইন রেকর্ডিং',
    'Results stored on immutable ledger': 'ফলাফল অপরিবর্তনীয় লেজারে সংরক্ষিত',
    'Credit Generation': 'ক্রেডিট জেনারেশন',
    'GramCredits issued based on verified impact': 'যাচাইকৃত প্রভাবের ভিত্তিতে গ্রামক্রেডিট জারি করা হয়',
    'Verification Benefits': 'যাচাইকরণ সুবিধা',
    '95%+ accuracy with AI verification': 'AI যাচাইকরণের সাথে 95%+ নির্ভুলতা',
    '24-48 hour verification time': '24-48 ঘন্টা যাচাইকরণ সময়',
    'Transparent blockchain recording': 'স্বচ্ছ ব্লকচেইন রেকর্ডিং',
    'Instant credit generation': 'তাৎক্ষণিক ক্রেডিট জেনারেশন',
    'Global marketplace access': 'বিশ্বব্যাপী বাজার অ্যাক্সেস',
    'Real-time impact tracking': 'রিয়েল-টাইম প্রভাব ট্র্যাকিং',
    'Live Satellite Feed': 'লাইভ স্যাটেলাইট ফিড',
    'Real-time satellite imagery of your project locations': 'আপনার প্রকল্প অবস্থানের রিয়েল-টাইম স্যাটেলাইট চিত্র',
    'Environmental Metrics': 'পরিবেশগত মেট্রিক্স',
    'Carbon Sequestration': 'কার্বন সিকোয়েস্ট্রেশন',
    'Energy Generation': 'শক্তি উৎপাদন',
    'Water Saved': 'পানি সংরক্ষিত',
    'Soil Health': 'মাটির স্বাস্থ্য',
    'Project Status': 'প্রকল্পের অবস্থা',
    'AI Insights': 'AI অন্তর্দৃষ্টি',
    'Recommendation': 'সুপারিশ',
    'Achievement': 'অর্জন',
    'lessons completed': 'সম্পূর্ণ পাঠ',
    'credits available': 'উপলব্ধ ক্রেডিট',
    'per credit': 'প্রতি ক্রেডিট',
    'Search sellers, projects, or locations...': 'বিক্রেতা, প্রকল্প বা অবস্থান অনুসন্ধান করুন...',
    'Credits Earned': 'অর্জিত ক্রেডিট',
    'Type': 'ধরন',
    'Confidence': 'আস্থা',
    'Register & Verify': 'নিবন্ধন এবং যাচাইকরণ',
    'Sign up and verify your farming activities through our AI system': 'আমাদের AI সিস্টেমের মাধ্যমে সাইন আপ করুন এবং আপনার কৃষি কার্যক্রম যাচাই করুন',
    'Take Climate Action': 'জলবায়ু পদক্ষেপ নিন',
    'Plant trees, adopt solar energy, or restore ecosystems': 'গাছ লাগান, সৌর শক্তি গ্রহণ করুন বা ইকোসিস্টেম পুনরুদ্ধার করুন',
    'Get Verified': 'যাচাইকৃত হন',
    'AI and satellite technology verify your environmental impact': 'AI এবং স্যাটেলাইট প্রযুক্তি আপনার পরিবেশগত প্রভাব যাচাই করে',
    'Earn Credits': 'ক্রেডিট অর্জন করুন',
    'Receive GramCredits and trade them in the global marketplace': 'গ্রামক্রেডিট গ্রহণ করুন এবং বিশ্বব্যাপী বাজারে তাদের ব্যবসা করুন',
    'Water Conservation': 'পানি সংরক্ষণ',
    'Soil Conservation': 'মাটি সংরক্ষণ',
    'Waste Management': 'বর্জ্য ব্যবস্থাপনা',
    'Energy Efficiency': 'শক্তি দক্ষতা',
    'Introduction to Carbon Credits': 'কার্বন ক্রেডিটের পরিচয়',
    'Learn the basics of carbon markets and how they work': 'কার্বন বাজারের মূল বিষয় এবং তারা কীভাবে কাজ করে তা শিখুন',
    'Sustainable Farming Practices': 'টেকসই কৃষি অনুশীলন',
    'Modern techniques for eco-friendly agriculture': 'পরিবেশ বান্ধব কৃষির জন্য আধুনিক কৌশল',
    'Renewable Energy Systems': 'নবায়নযোগ্য শক্তি সিস্টেম',
    'Solar, wind, and biogas solutions for farmers': 'কৃষকদের জন্য সৌর, বায়ু এবং বায়োগ্যাস সমাধান',
    'Water Conservation Techniques': 'পানি সংরক্ষণ কৌশল',
    'Efficient irrigation and rainwater harvesting': 'দক্ষ সেচ এবং বৃষ্টির পানি সংগ্রহ',
    'Blockchain Fundamentals': 'ব্লকচেইন মৌলিক বিষয়',
    'Understanding blockchain technology for carbon credits': 'কার্বন ক্রেডিটের জন্য ব্লকচেইন প্রযুক্তি বোঝা',
    'Climate Change Adaptation': 'জলবায়ু পরিবর্তন অভিযোজন',
    'Preparing your farm for climate resilience': 'জলবায়ু স্থিতিস্থাপকতার জন্য আপনার খামার প্রস্তুত করা',
    'First Steps': 'প্রথম পদক্ষেপ',
    'Complete your first lesson': 'আপনার প্রথম পাঠ সম্পূর্ণ করুন',
    'Knowledge Seeker': 'জ্ঞান অন্বেষণকারী',
    'Complete 5 lessons': '5টি পাঠ সম্পূর্ণ করুন',
    'Carbon Expert': 'কার্বন বিশেষজ্ঞ',
    'Master carbon credit fundamentals': 'কার্বন ক্রেডিট মৌলিক বিষয়ে দক্ষতা অর্জন করুন',
    'Sustainable Farmer': 'টেকসই কৃষক',
    'Complete all farming courses': 'সব কৃষি কোর্স সম্পূর্ণ করুন',
    'Community Leader': 'কমিউনিটি নেতা',
    'Help 10 other farmers': '10 জন অন্য কৃষককে সাহায্য করুন',
    'Green Pioneer': 'গ্রিন পায়োনিয়ার',
    'Complete all courses': 'সব কোর্স সম্পূর্ণ করুন',
    'Total Labels': 'মোট লেবেল',
    'Projects Completed': 'সম্পূর্ণ প্রকল্প',
    'Income Generated': 'উৎপন্ন আয়',
    'completed': 'সম্পূর্ণ',
    'Monthly Tree Planting': 'মাসিক গাছ রোপণ',
    'Plant 1000 trees as a community': 'একটি কমিউনিটি হিসেবে 1000টি গাছ লাগান',
    'Solar Energy Drive': 'সৌর শক্তি অভিযান',
    'Install solar panels in 50 farms': '50টি খামারে সৌর প্যানেল স্থাপন করুন',
    'Join Challenge': 'চ্যালেঞ্জে যোগ দিন',
    'Voice Interface': 'ভয়েস ইন্টারফেস',
    'Press and hold to speak': 'কথা বলতে চেপে ধরুন',
    'Listening...': 'শুনছি...',
    'Processing...': 'প্রক্রিয়াকরণ...',
    'Speak now': 'এখন বলুন',
    'Voice command recognized': 'ভয়েস কমান্ড স্বীকৃত',
    'Language changed to': 'ভাষা পরিবর্তিত হয়েছে',
    'English': 'ইংরেজি',
    'Hindi': 'হিন্দি',
    'Telugu': 'তেলুগু',
    'Tamil': 'তামিল',
    'Bengali': 'বাংলা',
    'Gujarati': 'গুজরাতি',
    'Marathi': 'মারাঠি',
    'Punjabi': 'পাঞ্জাবি',
    'Kannada': 'কন্নড়',
    'Malayalam': 'মালয়ালাম'
  }
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};